config/routes.rb
Rails.application.routes.draw do
  resources :solicituds
  get 'home/index'

  devise_for :users
  #get 'pages/home'
  root  'home#index'
  get 'solicitar' => 'solicituds#new'
  get 'about' => 'pages#about'
  get 'admin' => 'pages#home'
  get 'semilla' => 'home#semilla'
  get 'emprendedor' => 'home#emprendedor'
  get 'fertilizante' => 'home#fertilizante'
  get 'maiz' => 'home#maiz'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/solicitud.rb
class Solicitud < ApplicationRecord

	def self.to_csv(options = {})
	  CSV.generate(options) do |csv|
	    csv << column_names
	    all.each do |solicitud|
	      csv << solicitud.attributes.values_at(*column_names)
	    end
	  end
	end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about

  end
end

app/controllers/solicituds_controller.rb
class SolicitudsController < ApplicationController
  before_action :set_solicitud, only: [:show, :edit, :update, :destroy]

  # GET /solicituds
  # GET /solicituds.json
  def index
    @solicituds = Solicitud.order(params[:sort])
    respond_to do |format|
      format.html
      format.csv { send_data @solicituds.to_csv }
      format.xls { send_data @solicituds.to_csv(col_sep: "\t") }
    end
  end

  # GET /solicituds/1
  # GET /solicituds/1.json
  def show
  end

  # GET /solicituds/new
  def new
    @solicitud = Solicitud.new
  end

  # GET /solicituds/1/edit
  def edit
  end

  def order_name
    @solicitud = Solicitud.order(nombre: :DESC)
  end

  # POST /solicituds
  # POST /solicituds.json
  def create
    @solicitud = Solicitud.new(solicitud_params)

    respond_to do |format|
      if @solicitud.save
        format.html { redirect_to root_path, notice: 'Su solicitud ha sido creada satisfactoriamente.' }
        format.json { render :show, status: :created, location: @solicitud }
      else
        format.html { render :new }
        format.json { render json: @solicitud.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /solicituds/1
  # PATCH/PUT /solicituds/1.json
  def update
    respond_to do |format|
      if @solicitud.update(solicitud_params)
        format.html { redirect_to @solicitud, notice: 'Solicitud se ha editado satisfactoriamente.' }
        format.json { render :show, status: :ok, location: @solicitud }
      else
        format.html { render :edit }
        format.json { render json: @solicitud.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /solicituds/1
  # DELETE /solicituds/1.json
  def destroy
    @solicitud.destroy
    respond_to do |format|
      format.html { redirect_to solicituds_url, notice: 'Solicitud ha sido eliminada.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_solicitud
      @solicitud = Solicitud.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def solicitud_params
      params.require(:solicitud).permit(:nombre, :ap, :edad, :direccion, :telefono, :email, :programa)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/solicituds_helper.rb
module SolicitudsHelper
end

app/views/home/emprendedor.html.erb
<div class="container">
	<div class="col-md-6">
		<b><h2>GENTE EMPRENDEDORA:</h2></b>
		<p>Apoyar a gente emprendedora con proyectos que tengan impacto en la sociedad con la finalidad de apoyar a jóvenes con talento en el municipio. Logrando asi: incrementar el apoyo a jóvenes mediante apoyos económicos, verificar el seguimiento de los proyectos y crear proyectos de innovación.</p>
		<b><h2>Requisitos:</h2></b>
		<ul>
			<li>•	Ser originario del municipio (San Damián Texoloc)</li>
			<li>•	Documentación del proyecto</li>
			<li>•	1 Copia de la credencial de elector</li>
			<li>•	1 Copia del acta de nacimiento </li>
			<li>•	1 Copia la curp</li>
			<li>•	1 copia del Comprobante de domicilio</li>
		</ul>
	</div>
	<div class="col-md-6">
		<center><%= image_tag "conf.jpg", :width => "450", :height => "300" %></center>
		<br><br>
		<b><p>Si está interesado en este o en alguno de nuestros proyectos puede solicitar el apoyo dando click en el siguiente botón:</p></b>

		<center>
		<%= link_to 'Solicitar apoyo', solicitar_path, :class => "btn btn-primary btn-lg" %>
		</center>
	</div>
</div>

app/views/home/fertilizante.html.erb
<div class="container">
	<div class="col-md-6">
		<b><h2>PROYECTOS DE FERTILIZANTES:</h2></b>
		<p>Los apoyos serán destinados a personas físicas que se dediquen a actividades agrícolas, de bajos ingresos que satisfaga las necesidades de alimentos de las familias del campo y los excedentes se destinen al comercio.</p>
		<b><h2>Requisitos:</h2></b>
		<ul>
			<li>•	Ser originario del municipio (San Damián Texoloc)</li>
			<li>•	Contar con un mínimo de una hectárea de terreno</li>
			<li>•	2 Copia de las escrituras del terreno</li>
			<li>•	2 Copia de INE de beneficiario</li>
			<li>•	2 Copia de acta de nacimiento</li>
			<li>•	2 Copia de curp</li>
			<li>•	2 Copia de comprobante de domicilio</li>
		</ul>
	</div>
	<div class="col-md-6">
		<center><%= image_tag "nota.jpg", :width => "450", :height => "300"%></center>
		<br><br>
		<b><p>Si está interesado en este o en alguno de nuestros proyectos puede solicitar el apoyo dando click en el siguiente botón:</p></b>

		<center>
		<%= link_to 'Solicitar apoyo', solicitar_path, :class => "btn btn-primary btn-lg" %>
		</center>
	</div>
</div>

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Agropecuarios</title>
  </head>
  <body>

    <div class="loader"></div>
    <div id="myDiv">
    <!--HEADER-->
    <div class="header">
      <div class="bg-color">
        <div class="wrapper">
        <div class="container">
          <div class="row">
            <div class="banner-info text-center wow fadeIn delay-05s">
              <h1 class="bnr-title"><span> Dirección de desarrollo Agropecuario</span></h1>
              <h2 class="bnr-sub-title">San Damian Texoloc,Tlaxcala</h2>
              <p class="bnr-para">*******************</p>
            </div>
        </div>
      </div>
    </div>
    </div>
    </div>
    <!--/ HEADER-->
    <!---->
   <section id="feature" class="section-padding wow fadeIn delay-05s">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="service-item">
              <center><h3><span>Conocenos</span></h3></center>
            </div>
          </div>
          <div class="col-md-6 col-sm-6 col-xs-12" >
            <div class="wrap-item text-center">
                <h3 class="pad-bt15">Misión </h3>
                 <p><br>Planear e impulsar el desarrollo integral y sustentable de las actividades agropecuarias y forestales,
    			       <br> con visión empresarial y responsabilidad social, para contribuir al mejoramiento de las condiciones de vida de los 
    			       productores del campo mexiquense y a la seguridad alimentaria.</p>
            </div>
          </div>
          <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="wrap-item text-center">
              <h3 class="pad-bt15">Visión </h3>
              <p><br>La Secretaría de Desarrollo Agropecuario será una agrupación que logre impulsar, 
      			  desarrollar y fortalecer las acciones e iniciativas,<br> preferentemente en zonas con potencial productivo medio y alto, 
      			  en cultivos <br>propiciando la participación de los tres niveles de gobierno, el sector privado, los productores y sus organizaciones, 
      			  en el cambio de paradigmas que requiere el campo mexiquense, ante las nuevas realidades del mundo globalizado.</p>
            </div>
          </div>
    </section>    
    <!---->
    <section id="portfolio" class="section-padding wow fadeInUp delay-05s">
      <div class="container">
        <div class="row">
          <div class="col-md-12 text-center">
            <h2 class="service-title pad-bt15">Proyectos Aplicados</h2>
            <hr class="bottom-line">
          </div>
          <div class="col-md-6 col-sm-6 col-xs-12 portfolio-item padding-right-zero mr-btn-15">
            <figure>
            <%= image_tag "evi1.jpg", :width => "450", :height => "300" %>
              <figcaption>
                  <h2>Proyecto de Semilla</h2>
                  <p>Se siembran alrededor de 130 hectáreas de maíz,zacate,sorgo y alfalfa, 
        				  plantaciones que se encuentran en un radio aproximado de 3km, beneficiando
        				  al sector de ganado.</p>
                  <br>
                  <center>
                  <%= link_to 'Ver Más', semilla_path, :class => "btn btn-default btn-lg" %>
                  </center>
              </figcaption>
            </figure>
          </div>
          <div class="col-md-6 col-sm-6 col-xs-12 portfolio-item padding-right-zero mr-btn-15">
            <figure>
            	<%= image_tag "conf.jpg", :width => "450", :height => "300" %>
              <figcaption>
                  <h2>Gente emprendedora</h2>
                  <p>Se capacitan a las personas para que pueda generar una mejor produccion, 
				          se da a conocer los factores que intervienen en el proceso para tener mayores beneficios .</p>
                  <br>
                  <center>
                  <%= link_to 'Ver Más', emprendedor_path, :class => "btn btn-default btn-lg" %>
                  </center>
              </figcaption>
            </figure>
          </div>
          <div class="col-md-6 col-sm-6 col-xs-12 portfolio-item padding-right-zero mr-btn-15">
            <figure>
            	<%= image_tag "evi3.jpg", :width => "450", :height => "300" %>
              <figcaption>
                  <h2>Produccion de Maiz</h2>
                  <p>Cada año se beneficia a la poblacion con la siembra de maiz hibrido .</p>
                  <br>
                  <center>
                  <%= link_to 'Ver Más', maiz_path, :class => "btn btn-default btn-lg" %>
                  </center>
              </figcaption>
            </figure>
          </div>
          <div class="col-md-6 col-sm-6 col-xs-12 portfolio-item padding-right-zero mr-btn-15">
            <figure>
              <%= image_tag "nota.jpg", :width => "450", :height => "300"%>
              <figcaption>
                  <h2>Proyectos de fertilizantes</h2>
                  <p>Se efectuar un análisis de suelos es determinar la oferta de nutrientes del lote, para que, junto con la extracción de nutrientes (demanda) se puede efectuar un balance y establecer las cantidades a agregar como fertilizantes.</p>
                  <br>
                  <center>
                  <%= link_to 'Ver Más', fertilizante_path, :class => "btn btn-default btn-lg" %>
                  </center>
              </figcaption>
            </figure>
          </div>
        </div>
      </div>
    </section>
    <!---->
    <!---->
   
		
		
		
    <!---->
			<section id="contact" class="section-padding wow fadeInUp delay-05s">
      <div class="container">
        <div class="row">
          <div class="col-md-12 text-center white">
            <h2 class="service-title pad-bt15">Contacto</h2>
            <hr class="bottom-line white-bg">
          </div>
          <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="loction-info white">
              <div class="container">
                <span>
                  <i class="fa fa-map-marker fa-fw pull-left fa-2x"></i><p>Calle No <br>San Damian Texoloc, Tlax.</p>
                  <i class="fa fa-envelope-o fa-fw pull-left fa-2x"></i><p>municipio@gmail.com</p>
                  <i class="fa fa-phone fa-fw pull-left fa-2x"></i><p>cel: 233445555</p>
                </span>
              </div>
              
            </div>
          </div>
          <div class="col-md-6 col-sm-6 col-xs-12">
            <%= image_tag "conf.jpg", class:"img-responsive"%>
          </div>
         
            </div>
          </div>
    </section>
    <!---->
    <!----><br><br>
    <footer id="footer" class="bg-foot">
      <div class="container">
        <div class="row text-center white">
          <p> Creditos:</p>
          <div class="credits">
            <b>
            <p>Elia Pluma Mixcoatl</p>
            <p>Consuelo Tecpa García</p>
            <p>Brizeida Nájera Visoso</p>
            <p>Elizabeth Conde Netzathual</p>
            </b>
            <%= link_to 'Administrador', admin_path %>
            <div class="container">
              <%= link_to "Open modal", "#my-modal", :class => "btn", "data-toggle" => "modal" %>
              <div class="modal hide fade" id="my-modal" title="My modal">
                <div class="modal-header">
                  <button aria-hidden="true" class="close" data-dismiss="modal" type="button">×</button>
                  <h3 id="myModalLabel">Modal header</h3>
                </div>
                <div class="modal-body">
                  Modal Body
                </div>
                <div class="modal-footer">
                  <button aria-hidden="true" class="btn" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
        </div>
        </div>
      </div>
    </footer>
    <!---->
  </div>
  </body>
</html>

app/views/home/maiz.html.erb
<div class="container">
	<div class="col-md-6">
		<b><h2>PROYECTO PRODUCCIÓN  DE MAÍZ:</h2></b>
		<p>Incrementar la productividad de maíz en las comunidades rurales mediante el apoyo de semilla para la siembra de la misma, para obtener un cultivo prioritario con gran potencial en el mercado.</p>
		<b><h2>Requisitos:</h2></b>
		<ul>
			<li>•	Ser originario del municipio (San Damián Texoloc)</li>
			<li>•	Contar con un mínimo de una hectárea de terreno</li>
			<li>•	2 Copia de las escrituras del terreno</li>
			<li>•	2 Copia de INE de beneficiario</li>
			<li>•	2 Copia de acta de nacimiento</li>
			<li>•	2 Copia de curp</li>
			<li>•	2 Copia de comprobante de domicilio</li>
		</ul>
	</div>
	<div class="col-md-6">
		<center><%= image_tag "evi3.jpg", :width => "450", :height => "300" %></center>
		<br><br>
		<b><p>Si está interesado en este o en alguno de nuestros proyectos puede solicitar el apoyo dando click en el siguiente botón:</p></b>

		<center>
		<%= link_to 'Solicitar apoyo', solicitar_path, :class => "btn btn-primary btn-lg" %>
		</center>
	</div>
</div>

app/views/home/semilla.html.erb
<div class="container">
	<div class="col-md-6">
		<b><h2>PROYECTO DE SEMILLA:</h2></b>
		<p>Los apoyos serán destinados a personas físicas que se dediquen a actividades agrícolas con preferencia a productoras y productores de bajos ingresos especialmente dedicadas a la producción de frijol para el consumo de las familias del municipio. El concepto de apoyo contara con un paquete de semilla para maíz,zacate,sorgo y alfalfa.</p>
		<b><h2>Requisitos:</h2></b>
		<ul>
			<li>•	Ser originario del municipio (San Damián Texoloc)</li>
			<li>•	Contar con un mínimo de una hectárea de terreno</li>
			<li>•	2 Copia de las escrituras del terreno</li>
			<li>•	2 Copia de INE de beneficiario</li>
			<li>•	2 Copia de acta de nacimiento</li>
			<li>•	2 Copia de curp</li>
			<li>•	2 Copia de comprobante de domicilio</li>
		</ul>
	</div>
	<div class="col-md-6">
		<center><%= image_tag "evi1.jpg", :width => "450", :height => "300" %></center>
		<br><br>
		<b><p>Si está interesado en este o en alguno de nuestros proyectos puede solicitar el apoyo dando click en el siguiente botón:</p></b>

		<center>
		<%= link_to 'Solicitar apoyo', solicitar_path, :class => "btn btn-primary btn-lg" %>
		</center>
	</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Menú</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Inicio", root_path %></li>
        <li class=""><a href="/home/index#feature">Quienes somos</a></li>
        <li class=""><a href="/home/index#portfolio">Programas</a></li>
        <li class=""><%= link_to 'Registrarse', solicitar_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dirección Agropecuaria</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
  	<%= render 'layouts/header' %>
    <br>
  	<div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>
		<%= yield %>
  	</div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Acerca de nosotros</h1>

app/views/pages/home.html.erb
<div class="jumbotron center">
	<h1>Bienvenido a Dirección Agropecuaria</h1>

	<% if user_signed_in? %>
      <%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete, class:'btn btn-danger btn-lg' %>
      <%= link_to 'Ver registros', solicituds_path, class:'btn btn-success btn-lg' %>
    <% else %>
      <%= link_to "Iniciar Sesión", new_user_session_path, class:'btn btn-success btn-lg' %>
    <% end %>
	
</div>

app/views/solicituds/_form.html.erb
<div class="container">
<%= form_with(model: solicitud, local: true) do |form| %>
  <% if solicitud.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(solicitud.errors.count, "error") %> prohibited this solicitud from being saved:</h2>

      <ul>
      <% solicitud.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-4">
      <div class="field">
        <%= form.label :nombre, "Nombre(s)" %>
        <%= form.text_field :nombre, id: :solicitud_nombre %>
      </div>
    </div>

    <div class="col-md-4">
      <div class="field">
        <%= form.label :ap, "Apellidos" %>
        <%= form.text_field :ap, id: :solicitud_ap %>
      </div>
    </div>

    <div class="col-md-4">
      <div class="field">
        <%= form.label :edad, "Edad" %>
        <%= form.number_field :edad, id: :solicitud_edad %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <div class="field">
        <%= form.label :direccion, "Dirección" %>
        <%= form.text_field :direccion, id: :solicitud_direccion %>
      </div>
    </div>

    <div class="col-md-4">
      <div class="field">
        <%= form.label :telefono, "Teléfono" %>
        <%= form.number_field :telefono, id: :solicitud_telefono %>
      </div>
    </div>
  </div>  

  <div class="row">
    <div class="col-md-4">
      <div class="field">
        <%= form.label :email, "Correo (si no tiene escribir: Sin Correo)" %>
        <%= form.text_field :email, id: :solicitud_email %>
      </div>
    </div>

    <div class="col-md-4">
      <div class="field">
        <%= form.label :programa, "Elija el programa que solicita" %>
        <%= form.select :programa, options_for_select([["Proyecto de Semilla", "Proyecto de Semilla"], ["Gente emprendedora", "Gente emprendedora"], ["Produccion de Maiz", "Produccion de Maiz"], ["Proyectos de fertilizantes", "Proyectos de fertilizantes"]]) %>
      </div>
    </div>
  </div>  
  
  <div class="row">
    <div class="col-md-12">
      <%= form.submit %>
    </div>
  </div>
  
<% end %>
</div>

app/views/solicituds/edit.html.erb
<h1>Editar Solicitud</h1>

<%= render 'form', solicitud: @solicitud %>

<%= link_to 'Ver', @solicitud %> |
<%= link_to 'Volver', solicituds_path %>

app/views/solicituds/index.html.erb
<h1>Solicitudes</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= link_to "ID", :sort => "id" %></th>
      <th><%= link_to "Nombre", :sort => "nombre" %></th>
      <th><%= link_to "Apellidos", :sort => "ap" %></th>
      <th><%= link_to "Edad", :sort => "edad" %></th>
      <th><%= link_to "Dirección", :sort => "direccion" %></th>
      <th><%= link_to "Teléfono", :sort => "telefono" %></th>
      <th><%= link_to "Correo", :sort => "email" %></th>
      <th><%= link_to "Programa", :sort => "programa" %></th>
      <th colspan="3">Opciones</th>
    </tr>
  </thead>

  <tbody>
    <% @solicituds.each do |solicitud| %>
      <tr>
        <td><%= solicitud.id %></td>
        <td><%= solicitud.nombre %></td>
        <td><%= solicitud.ap %></td>
        <td><%= solicitud.edad %></td>
        <td><%= solicitud.direccion %></td>
        <td><%= solicitud.telefono %></td>
        <td><%= solicitud.email %></td>
        <td><%= solicitud.programa %></td>
        <td><%= link_to 'Ver', solicitud, class:'btn btn-primary white' %></td>
        <td><%= link_to 'Editar', edit_solicitud_path(solicitud), class:'btn btn-success white' %></td>
        <td><%= link_to 'Eliminar', solicitud, method: :delete, class:'btn btn-danger white', data: { confirm: 'Esta seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Solicitud', solicitar_path, class:'btn btn-primary btn-lg white' %>
<p>Download:</p>
  <%= link_to "Excel", solicituds_path(format: "xls") %>

app/views/solicituds/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Nombre</Data></Cell>
        <Cell><Data ss:Type="String">Apellidos</Data></Cell>
        <Cell><Data ss:Type="String">Edad</Data></Cell>
        <Cell><Data ss:Type="String">Dirección</Data></Cell>
        <Cell><Data ss:Type="String">Teléfono</Data></Cell>
        <Cell><Data ss:Type="String">Correo</Data></Cell>
        <Cell><Data ss:Type="String">Programa</Data></Cell>
      </Row>
    <% @solicituds.each do |product| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= product.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= product.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= product.ap %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= product.edad %></Data></Cell>
        <Cell><Data ss:Type="String"><%= product.direccion %></Data></Cell>
        <Cell><Data ss:Type="String"><%= product.telefono %></Data></Cell>
        <Cell><Data ss:Type="String"><%= product.email %></Data></Cell>
        <Cell><Data ss:Type="String"><%= product.programa %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/solicituds/new.html.erb
<h1>Nueva Solicitud</h1>

<%= render 'form', solicitud: @solicitud %>

app/views/solicituds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @solicitud.nombre %>
</p>

<p>
  <strong>Apellidos:</strong>
  <%= @solicitud.ap %>
</p>

<p>
  <strong>Edad:</strong>
  <%= @solicitud.edad %>
</p>

<p>
  <strong>Dirección:</strong>
  <%= @solicitud.direccion %>
</p>

<p>
  <strong>Teléfono:</strong>
  <%= @solicitud.telefono %>
</p>

<p>
  <strong>Email:</strong>
  <%= @solicitud.email %>
</p>

<p>
  <strong>Programa:</strong>
  <%= @solicitud.programa %>
</p>

<%= link_to 'Editar', edit_solicitud_path(@solicitud) %> |
<%= link_to 'Volver', solicituds_path %>